version: '3'

services:
  jupyter:
    image: 'jupyter/datascience-notebook:latest'
    container_name: jupyterlab_notebooks
    restart: always
    ports: 
      - '8888:8888'
      - '8889:8889'
    volumes:
      - jupyterlab_notebook:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB}
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
      
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio_storages
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SITE_NAME: ${MINIO_SITE_NAME}
      MINIO_SITE_REGION: ${MINIO_SITE_REGION}
      MINIO_API_REQUESTS_MAX: ${MINIO_API_REQUESTS_MAX}
      MINIO_API_REQUESTS_DEADLINE: ${MINIO_API_REQUESTS_DEADLINE}
      
  postgres:
    image: 'postgres:latest'
    container_name: postgres_databases
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin_managements
    restart: always
    depends_on: 
      - postgres
    ports:
      - '5556:80'
    volumes:
      - pgadmin_management:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  superset:
    image: 'tylerfowler/superset:latest'
    container_name: superset_visualizations
    restart: always
    ports:
      - '8088:8088'
      - '8089:8089'
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PWD: ${ADMIN_PWD}
      ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME}
      ADMIN_LAST_NAME: ${ADMIN_LAST_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}

volumes:
  jupyterlab_notebook:
  minio_storage:
  postgres_database:
  pgadmin_management: